# Generated by Django 3.1.7 on 2021-04-04 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20210404_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='code',
            field=models.CharField(default='1E1237', max_length=6, unique=True),
        ),
    ]
